version: "3.8"

services:
  flask:
    build: .
    container_name: flask-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - Flask_ALLOWED_HOST=localhost
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKENDS=redis://redis:6379
      - REDIS_HOST=redis
    depends_on:
      - mongodb_container
      - redis
  celery:
    build: .
    command: celery -A app.celery worker -l info -P gevent
    volumes:
      - .:/usr/src/app
    depends_on:
      - flask
      - redis
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: "redis"
    ports:
      - "6379:6379"
volumes:
  mongodb_data_container:


