"""empty message

Revision ID: 6702aaef0e52
Revises: 5c696283c052
Create Date: 2022-10-10 17:48:17.492403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6702aaef0e52'
down_revision = '5c696283c052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
