version: "3.8"

services:
  flask:
    build: .
    container_name: flask-app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - DEBUG=1
      - FLASK_ALLOWED_HOST=localhost
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKENDS=redis://redis:6379
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb_container
    depends_on:
      - mongodb_container
      - redis
  celery:
    build: .
    command: celery -A app.celery worker -l info -P gevent
    volumes:
      - .:/usr/src/app
    depends_on:
      - flask
      - redis
  mongodb_container:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'ajinkya'
      MONGO_INITDB_ROOT_PASSWORD: '12345'
      MONGO_INITDB_DATABASE: 'movieapp'
    volumes:
      - log:/data/db
  redis:
    image: "redis"

volumes:
  log:


